### ISSUE TITLE
Unauthorized Request

### ISSUE THREAD

**Issue by fankes** [ZQDesigned/CharactersCode#3]
您的项目的 appdemo 目录完整地复制了我的项目中的全部代码，但您未使用相应许可证或在您的 README.md 进行说明，请加以补充其目的。
代码位置：https://github.com/ZQDesigned/CharactersCode/tree/master/appdemo

**Comment by ZQDesigned** [comment]
I will add the description into file Readme.md recently. I just use it to learn something about UI designing. Sorry for this unauthorize behavior.

**Comment by ZQDesigned** [comment]
I can't open Github web page on my phone, so I will add it when I go back home. Sorry again.

**Comment by fankes** [comment]
Never mind. Thank you for reply.

**Comment by ZQDesigned** [comment]
I have updated the file README.md just now. Is it suitable?

**Comment by fankes** [comment]
> I have updated the file README.md just now. Is it suitable?

OK fine thank you
